version: '3'

networks:
  web:
    external: true
  internal: 
    external: false
    
services:
  e-voiting:
    build:
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/e-voting
    ports:
      - 8000:8000
